# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
